name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: configure
      run: |
         sudo apt-get -y install wget libgmp-dev libmpfr-dev # libflint-dev
         wget https://www.flintlib.org/flint-2.6.3.tar.gz
         tar xf flint-2.6.3.tar.gz
         cd flint-2.6.3
         ./configure
         make
         sudo make install
         cd ..
         ./configure
    - name: make
      run: make
    - name: make check
      run: make check
