name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: configure
      run: |
         sudo apt-get -y install libgmp-dev libflint-dev
         ./configure
    - name: make
      run: make
    - name: make check
      run: make check
